apiVersion: apps/v1
kind: Deployment
metadata:
  name: Healthcare_app
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javaappcontainer
        image: ravighaddam/ravi-healthcare
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp-np-service
  labels:
    app: javawebapp
spec:
  type: NodePort
  selector:
    app: javawebapp

  ports:
    - port: 8082
      nodePort: 31000
      targetPort: 8082
